name: Test vistools

on:
  schedule:
    - cron: '0 22 * * *'
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
    type: choice

jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install vistools
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Code checks
        run: |
          pre-commit install --install-hooks
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            SKIP=no-commit-to-branch pre-commit run --all-files
          else
            pre-commit run --all-files
          fi

  test_suite:
    name: ${{ matrix.os-version }} python${{ matrix.python-version }}
    strategy:
      matrix:
        os-version: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]
    runs-on: ${{ matrix.os-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install vistools
        run: |
          python -m pip install --upgrade pip
          pip install .[pyvista,dev]
      - name: Setup headless display # Not needed for macOS
        uses: pyvista/setup-headless-display-action@v3
      - name: Test with pytest
        run: |
          pytest
